js_css_compressor.lo: /home/kufd/C++/jsCssCompressor/js_css_compressor.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/home/kufd/C++/jsCssCompressor $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /home/kufd/C++/jsCssCompressor/js_css_compressor.cpp -o js_css_compressor.lo 
compressor.lo: /home/kufd/C++/jsCssCompressor/compressor.class.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/home/kufd/C++/jsCssCompressor $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /home/kufd/C++/jsCssCompressor/compressor.class.cpp -o compressor.lo 
$(phplibdir)/js_css_compressor.la: ./js_css_compressor.la
	$(LIBTOOL) --mode=install cp ./js_css_compressor.la $(phplibdir)

./js_css_compressor.la: $(shared_objects_js_css_compressor) $(JS_CSS_COMPRESSOR_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_js_css_compressor) $(JS_CSS_COMPRESSOR_SHARED_LIBADD)

